// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDeX0l9v0mDAGfefYmoxcgagoaCQWVzPy0',
    appId: '1:970002585360:web:7bb4b3aa9a05ca1afd7795',
    messagingSenderId: '970002585360',
    projectId: 'soda-5th',
    authDomain: 'soda-5th.firebaseapp.com',
    storageBucket: 'soda-5th.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvd56yf3qfNSTp0i57Byke5acL708iIwA',
    appId: '1:970002585360:android:955df79b080f4c44fd7795',
    messagingSenderId: '970002585360',
    projectId: 'soda-5th',
    storageBucket: 'soda-5th.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDI_sDlRzaefcw4SNTyDNk2b0VyKxrIA94',
    appId: '1:970002585360:ios:7c259d2c8c833061fd7795',
    messagingSenderId: '970002585360',
    projectId: 'soda-5th',
    storageBucket: 'soda-5th.appspot.com',
    iosBundleId: 'com.example.welcomeToSoda5th',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDI_sDlRzaefcw4SNTyDNk2b0VyKxrIA94',
    appId: '1:970002585360:ios:afc2d55c2533af60fd7795',
    messagingSenderId: '970002585360',
    projectId: 'soda-5th',
    storageBucket: 'soda-5th.appspot.com',
    iosBundleId: 'com.example.welcomeToSoda5th.RunnerTests',
  );
}
